openapi: '3.1.0'
info:
  title: WMA Calculator API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
components:
  schemas:
    WorldMasterAthletics:
      type: object
      description: WMA
      items: 
        $ref: "#/components/schemas/AgeRatioList" 
    AgeRatioList:
      type: object
      description: List
      items:
        $ref: '#/components/schemas/AgeRatio'
    # https://stackoverflow.com/questions/46472543/specifying-multiple-types-for-additionalproperties-through-swagger-openapi
    AgeRatio:
      type: object
      description: AgeRatio
      properties: 
        event:
          $ref: "#/components/schemas/Event"
        gender: 
          $ref: "#/components/schemas/Gender"  
        age:
          type: integer
          description: The age of the athlete.
    Event:
      type: object
      description: Event
      properties: 
        name:
          type: string
          description: The name of the event.
        code:

        type:
          $ref: "#/components/schemas/EventType"  
    EventType:
      type: string
      description: The event type of the athlete age ratio group.
      enum: 
        - Time
        - Jump
        - Throw
    EventCode:
      type: string
      description: The event code of the athlete age ratio group.
      enum: 
        - 100m
        - 110mh
        - 200m
        - 400m
        - 800m
        - 1000m
        - 1500m
        - 3000m
        - 5000m
        - 10000m
        - Marathon
        - HalfMarathon    
    Gender:
      type: string
      description: The gender of the athlete age ratio group.
      enum: 
        - Male
        - Female
security: [] 
paths:
  /wma:
    get:
      operationId: abc
      summary: wma details
      responses:
        '400':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorldMasterAthletics"
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorldMasterAthletics"
                