name: build

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/pnpm/action-setup
      # https://stackoverflow.com/questions/74884763/pnpm-github-actions-flow
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          check-latest: true
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        
      - name: Build 
        run: pnpm build