name: build

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/pnpm/action-setup
      # https://stackoverflow.com/questions/74884763/pnpm-github-actions-flow
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build