name: build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        uses: actions/setup-node@v2
        with:
          node-version: '23'
          check-latest: true
      - run: npm install
      - run: npm run build