name: build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and Build
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          check-latest: true
          cache: 'npm'
      - run: npm ci
      - run: npm run build